server:
  port: 8080
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    connection-timeout: 60000
    keep-alive-timeout: 60000
    max-http-response-header-size: 65536
logging:
  level:
    root: DEBUG

Spring:
# jwt secret key 설정
  jwt:
    secret:
    tokenExpiry: 3600000
    refreshSecret:
    refreshTokenExpiry: 1209600000

# 암호화
encryption:
  keys:
    login:
    signup:
  ivs:
    login:
    signup:

# postgresql
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url:
    username:
    password:

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul






