server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    connection-timeout: 60000
    keep-alive-timeout: 60000
    max-http-response-header-size: 65536
logging:
  level:
    root: DEBUG

Spring:
  # jwt secret key 설정
  jwt:
    secret: nLTft3rpggbZvFSiSMN7wYyvmW7pApWpNAQsdl0WUtg=
    tokenExpiry: 3600000
    refreshSecret: C3insT0E5lSEJghgU4hfBEUhzcseBNQt/RJtT2LOKY4=
    refreshTokenExpiry: 1209600000

# 암호화
encryption:
  keys:
    signup: CSZaYqBII09U1AHa3HXvKXzXkyEZmDlmin7j+iQjwYE=
  ivs:
    signup: HJjyL305R6D4FOLSwojlMg==

# postgresql
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
    username: postgres.vjeftabbisgxwapfikgi
    password: '!tmvnswm123'
    hikari:
      maximum-pool-size: 10         # Transaction 모드는 더 많이 허용
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul