server:
  port: ${PORT:8080}

spring:
  profiles: # profiles 설정
    active: dev # 다른 설정이 없을 때 default 환경 값
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    time-zone: Asia/Seoul
  mvc:
    async:
      request-timeout: -1
#logging config
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.spoons.popparazzi: DEBUG  # 본인 코드는 상세히

    # SQL 로그만 보고 싶다면
    jdbc.sqlonly: DEBUG  # SQL만
    jdbc.resultsettable: DEBUG  # 결과도

    # 나머지는 조용히
    org.springframework: WARN
    org.apache: WARN
    com.zaxxer.hikari: ERROR
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true